'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {randomUUID}=require('node:crypto');
const {MeetingStore,markdown}=require('../store');
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'invis-store-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return new MeetingStore(dir);}
test('meetings, notes, original transcripts and answers survive restart',t=>{const store=setup(t),m=store.create({title:'Planning'});store.update(m.id,{notes:'Agenda: release'});store.addTurn(m.id,{id:'one',source:'meeting',text:'Alex will send the draft on Friday.',at:10});const fresh=new MeetingStore(store.directory);assert.equal(fresh.get(m.id).notes,'Agenda: release');assert.equal(fresh.list().meetings[0].title,'Planning');assert.equal(fresh.get(m.id).transcripts[0].text,'Alex will send the draft on Friday.');});
test('deduplication is per source and late turns are ordered',t=>{const store=setup(t),m=store.create();store.addTurn(m.id,{id:'one',source:'microphone',text:'Later',at:20});store.addTurn(m.id,{id:'one',source:'meeting',text:'Earlier',at:10});store.addTurn(m.id,{id:'one',source:'meeting',text:'Duplicate',at:10});assert.deepEqual(store.get(m.id).transcripts.map(t=>t.text),['Earlier','Later']);});
test('file access rejects traversal and invalid source input',t=>{const store=setup(t),m=store.create();assert.throws(()=>store.get('../../settings'));assert.throws(()=>store.audioPath(m.id,'../../settings'));assert.throws(()=>store.addTurn(m.id,{source:'admin',text:'No'}));assert.throws(()=>store.update(m.id,{notes:'x'.repeat(24001)}));});
test('unreadable meetings are reported and kept intact',t=>{const store=setup(t),id=randomUUID();fs.writeFileSync(store.file(id),'broken');assert.equal(store.list().unreadable,1);assert.equal(fs.readFileSync(store.file(id),'utf8'),'broken');});
test('delete removes only selected meeting and its recordings',t=>{const store=setup(t),m=store.create(),other=store.create(),audioId=randomUUID();m.recordings.push({id:audioId});store.save(m);const audio=store.audioPath(m.id,audioId);fs.writeFileSync(audio,'audio');store.remove(m.id);assert.equal(fs.existsSync(audio),false);assert.equal(store.get(other.id).id,other.id);});
test('export separates source material, generated analysis, and chat',t=>{const store=setup(t),m=store.create({title:'Design review'});m.notes='Agenda';m.transcripts=[{source:'meeting',text:'Let us consider Friday.',at:0}];m.analysis={summary:'Friday was proposed [T1].',decisions:[],actions:[{task:'Review',owner:'',due:'',evidence:'[T1]'}],questions:[]};m.answers=[{question:'When?',answer:'No deadline agreed.',evidence:['T1']}];const output=markdown(m);assert.match(output,/\[T1\] meeting/);assert.match(output,/Owner: Unassigned; Due: Not specified/);assert.match(output,/## Ask AI/);assert.match(output,/Let us consider Friday/);});
test('transcript limits fail before changing the saved document',t=>{const store=setup(t),m=store.create();store.addTurn(m.id,{source:'import',text:'a'.repeat(800000)});assert.throws(()=>store.addTurn(m.id,{source:'import',text:'b'.repeat(300000)}),/limit/);assert.equal(store.get(m.id).transcripts.length,1);});
test('late-arriving speech does not renumber existing evidence references',t=>{const store=setup(t),m=store.create();store.addTurn(m.id,{id:'later',source:'meeting',text:'Decision',at:20});store.addTurn(m.id,{id:'earlier',source:'microphone',text:'Proposal',at:10});const saved=store.get(m.id);assert.equal(saved.transcripts[0].ref,'T2');assert.equal(saved.transcripts[1].ref,'T1');assert.match(markdown(saved),/\[T1\] meeting/);});
